apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dotnet-react-dapr-2022-05-30t16-35-23
spec:
  encryptedData:
    .dockerconfigjson: AgAWhxLu+DCFn/AaLrBlAUvAOzjHlDdSLVr4WPchszO1LvOoM2EFQWHLnC6jPryVuL0EWKO6tevPJ9Ge8/u7u32YPOHzQEaNTQiC+f5FzjLzxVx0guzDf/X8HjIflnilJo1u1uh9zUsJ4DLej0yCLTiFKdU3JLb/HQ4ywr1qe6N0CptZrAj96SbVSlPgANUEHTppx2/ATPDLMOPOUlZngcILeRDrvCKnrg6g4QJDZxw5os9xH1P4bzHqFLxE/bO2Uia7IzwIn+DIeD/vgPAknzo+uDGSZhrhHjRJSJsmJ21O2hDcP1/4inIX/zLsaFd2I3moKi27tT/RTXOwebKLg3VhgcSLgHTAszYetWb2F9sDA5eIgPiKr0c6J/ftgDgJgvd4+X9k1OtEuJJub1mMfR+lslCKoaBsjH7M7Lgx8sR6SNnNrol6sPCc32WbHZwh+6kRM1+jBirVvqJ2w0HQLiiq4PJFKXfLcgJELyaBc7Ok0z9ELbP7QGVc+TQoFxoc1eVeszOJ/WcZWEfee5wNnLTK/f373ebTiMUGgqN9RmBgdfEpE5pX8Z25M/RRk7Jpb56PU8rBZOmgJ8UgAe7XyWKBQ/oVHggX3jTKp0NCShRWpgGPl/qwLaZXGxSRWaHNBAR8GxfwY0hNWzRC679CDdFsB77CpMvLeP9JFYHPH+mWgOQ4b+A3ZezAbRjbUmqFfIfeRHbcMYcxMd1nwUkThImjdoaSsj/qOix0p5SUmPABe/5JOed97eSut1v6t0sim7b80UVWjX4nnJx6xr/v2aZS/+D+KN0MZnItpB4f5gYiickYlwXyjGVz5l9ZepBbjLEMxIKKGfT/+Jc+gevk7Wv+gc6oaHp2z+4/3aJ1PlkyCh5vk+FCK5nSZj0C+1HbhjinEIcFMkGNKxGzJnAzcjqavfVw5nMjU8kKFKcPA5Sw2KXyUuUZO3gZIHGUneim15w=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dotnet-react-dapr-2022-05-30t16-35-23
    type: kubernetes.io/dockerconfigjson

